### ISSUE TITLE
end-to-end tests fail when running locally

### ISSUE THREAD

**Issue by martinpitt** [weldr/welder-web#166]
I am following the [end-to-end test README](https://github.com/weldr/welder-web/blob/master/test/end-to-end/README.md) to try and run these on my host, instead of building a container first and running them there (this takes a magnitude more time, and cannot be done when moving into Cockpit's tests).

"Have both bdcs-api-rs and welder-web running on localhost" → I believe I do have that. http://localhost:4000/api/v0/test works, it comes from the running API container:

    4d6d4a958763        welder/bdcs-api-rs:latest   "/usr/local/bin/en..."   2 weeks ago         Up 43 minutes                 0.0.0.0:4000->4000/tcp   api

http://localhost:3000/ works as well, that's coming from an `npm run start` from the source tree. And yet I get nothing but failures:
```
❱❱❱ npm run test

> weldr-web-end-to-end-tests@0.0.0 test /home/martin/upstream/welder-web/test/end-to-end
> jest --runInBand --forceExit

(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: .wait() timed out after 30000msec
(node:810) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: .wait() timed out after 30000msec
(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: .wait() timed out after 30000msec
 FAIL  test/test_editRecipe.js (256.794s)
  ● Edit Recipe Page › Single Word Recipe Name Scenario › Menu Nav Bar Check #acceptance › should show a recipe name with a correct link address @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Title Bar Check #acceptance › should show a recipe name title @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Title Bar Check #acceptance › should have Create Composition button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For ostree #acceptance › should pop up Create Composition window by clicking Create Compostion button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For ostree #acceptance › should have toast notification pop up when new composition added @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For iso #acceptance › should pop up Create Composition window by clicking Create Compostion button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For iso #acceptance › should have toast notification pop up when new composition added @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For ami #acceptance › should pop up Create Composition window by clicking Create Compostion button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For ami #acceptance › should have toast notification pop up when new composition added @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For qcow2 #acceptance › should pop up Create Composition window by clicking Create Compostion button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For qcow2 #acceptance › should have toast notification pop up when new composition added @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For vhdx #acceptance › should pop up Create Composition window by clicking Create Compostion button @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Create Composition Test For vhdx #acceptance › should have toast notification pop up when new composition added @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Export Recipe To Manifest Test #acceptance › should pop up dropdown-menu by clicking ":" button

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Export Recipe To Manifest Test #acceptance › should pop up Export Recipe window by clicking "Export"

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Export Recipe To Manifest Test #acceptance › should copy and paste correct components

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Edit Recipe Page › Single Word Recipe Name Scenario › Save Recipe Test #acceptance › should have toast notification pop up when Save button clicked @edit-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: expect(received).toBe(expected)

Expected value to be (using ===):
  ""
Received:
  "https://github.com/weldr/welder-web/blob/master/test/end-to-end/README.md"
 FAIL  test/test_recipes.js (63.392s)
  ● Recipes Page › Recipe List › Single Word Recipe Name Scenario › Export Recipe To Manifest Test #acceptance › should copy and paste correct components

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

(node:810) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: expect(received).toBe(expected)

Expected value to be (using ===):
  ""
Received:
  "http://localhost:4000/api/v0/test"
 FAIL  test/test_viewRecipe.js (60.7s)
  ● View Recipe Page › Single Word Recipe Name Scenario › Recipe page - Export Recipe To Manifest Test #acceptance › should copy and paste correct components

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

 FAIL  test/test_createRecipe.js (31.703s)
  ● Create Recipe Page › Input Data Validation Test › Required Field Missing #acceptance › should show alert message by clicking Save button when create recipe without name @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Create Recipe Page › Input Data Validation Test › Required Field Missing #acceptance › should show alert message by clicking Enter key when create recipe without name @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Create Recipe Page › Input Data Validation Test › Required Field Missing #acceptance › should show alert message by changing focus to description input @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Create Recipe Page › Input Data Validation Test › Simple Valid Input Test #acceptance › should switch to Edit Recipe page - recipe creation success @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Create Recipe Page › Input Data Validation Test › Simple Valid Input Test #acceptance › should switch to Edit Recipe page - recipe creation success @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

  ● Create Recipe Page › Input Data Validation Test › Simple Valid Input Test #acceptance › should switch to Edit Recipe page - recipe creation success @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)

 FAIL  test/test_importSanity.js
  ● Imported Content Sanity Testing › displayed count should match distinct count from DB

    TypeError: Cannot read property 'each' of undefined
      
      at Object.<anonymous> (test/test_importSanity.js:52:8)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 5 failed, 5 total
Tests:       24 failed, 35 passed, 59 total
Snapshots:   0 total
Time:        415.246s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weldr-web-end-to-end-tests@0.0.0 test: `jest --runInBand --forceExit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weldr-web-end-to-end-tests@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martin/.npm/_logs/2017-10-24T06_53_15_909Z-debug.log
```

What am I doing wrong? How do you developers run the integration tests?

**Comment by martinpitt** [comment]
The log file mentioned in the output isn't particularly interesting:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'test' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle weldr-web-end-to-end-tests@0.0.0~pretest: weldr-web-end-to-end-tests@0.0.0
6 info lifecycle weldr-web-end-to-end-tests@0.0.0~test: weldr-web-end-to-end-tests@0.0.0
7 verbose lifecycle weldr-web-end-to-end-tests@0.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle weldr-web-end-to-end-tests@0.0.0~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/martin/upstream/welder-web/test/end-to-end/node_modules/.bin:/home/martin/bin:/home/martin/.local/bin:/usr/lib/ccache:/home/martin/ubuntu/ubuntu-archive-tools:/home/martin/bin:/home/martin/bin:/home/martin/.local/bin:/usr/lib/ccache:/home/martin/ubuntu/ubuntu-archive-tools:/home/martin/bin:/home/martin/bin:/home/martin/.local/bin:/usr/lib/ccache:/home/martin/ubuntu/ubuntu-archive-tools:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
9 verbose lifecycle weldr-web-end-to-end-tests@0.0.0~test: CWD: /home/martin/upstream/welder-web/test/end-to-end
10 silly lifecycle weldr-web-end-to-end-tests@0.0.0~test: Args: [ '-c', 'jest --runInBand --forceExit' ]
11 silly lifecycle weldr-web-end-to-end-tests@0.0.0~test: Returned: code: 1  signal: null
12 info lifecycle weldr-web-end-to-end-tests@0.0.0~test: Failed to exec test script
13 verbose stack Error: weldr-web-end-to-end-tests@0.0.0 test: `jest --runInBand --forceExit`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid weldr-web-end-to-end-tests@0.0.0
15 verbose cwd /home/martin/upstream/welder-web/test/end-to-end
16 verbose Linux 4.13.8-300.fc27.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "test"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error weldr-web-end-to-end-tests@0.0.0 test: `jest --runInBand --forceExit`
22 error Exit status 1
23 error Failed at the weldr-web-end-to-end-tests@0.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by atodorov** [comment]
@henrywang I think working on COMPOSER-80 will fix this.

**Comment by martinpitt** [comment]
COMPOSER-80 is only about test_importSanity.js, isn't it? This happens with just a single test too:
```
❱❱❱ node_modules/.bin/jest -i -t 'success @create-recipe-page'
 FAIL  test/test_createRecipe.js (15.177s)
  ● Create Recipe Page › Input Data Validation Test › Simple Valid Input Test #acceptance › should switch to Edit Recipe page - recipe creation success @create-recipe-page

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:471:11)
      at tryOnTimeout (timers.js:306:5)
      at Timer.listOnTimeout (timers.js:266:5)


Test Suites: 1 failed, 4 skipped, 1 of 5 total
Tests:       1 failed, 58 skipped, 59 total
Snapshots:   0 total
Time:        17.779s
Ran all test suites with tests matching "success @create-recipe-page".
[long hang, Control-C]
```

**Comment by martinpitt** [comment]
Running a rather short test with nightmare debugging at least sheds some light which assertion is failing:
```
❱❱❱ DEBUG=nightmare:actions jest -i -t 'Simple Valid Input Test #acceptance'
  nightmare:actions .wait() for button[data-target="#cmpsr-modal-crt-recipe"] element +0ms
  nightmare:actions .click() on button[data-target="#cmpsr-modal-crt-recipe"] +35ms
  nightmare:actions .wait() for fn +62ms
  nightmare:actions .insert() automation into div[id="cmpsr-modal-crt-recipe"] #textInput-modal-markup +257ms
  nightmare:actions .insert() UI automation recipe into div[id="cmpsr-modal-crt-recipe"] #textInput2-modal-markup +27ms
  nightmare:actions .click() on div[id="cmpsr-modal-crt-recipe"] .modal-footer .btn-primary +14ms
  nightmare:actions .wait() for .cmpsr-panel__body--sidebar .cmpsr-list-pf__compacted .list-pf-item element +34ms
```
I. e. this is timing out:
```js
          .wait(editRecipePage.componentListItemRootElement)
```
but at least it gets past the initial waits and clicks. Apparently clicking on the save button does something wrong.

This shows two more bad failure modes of the tests:

 * The "global" `jasmine.DEFAULT_TIMEOUT_INTERVAL` is shorter than nightmare's default `waitTimeout`, so that there are no useful backtraces.

 * Any error from the tests, like an error from `wait()` are not propagated/shown properly, and one always just gets the above general jasmine timeout as the `done()` callback is never reached.

With a [hack](https://paste.fedoraproject.org/paste/f6Yy7flb59tE6r60xakwZw) I was able to get a screenshot:
![screenshot](https://user-images.githubusercontent.com/200109/32366745-cd84b8ee-c07f-11e7-9f1a-cdb47a06e810.png)

I suppose the failure happens because the welder-web instance in electron does not see any packages?

**Comment by martinpitt** [comment]
I tried this manually in firefox, again with `welder/bdcs-api-rs:latest` running in docker, the web UI running from `npm run start`. There I *do* see packages, but clicking on "Save" pops up the "automation: Saving recipe" bubble and this never goes away:

![welder](https://user-images.githubusercontent.com/200109/32367019-ea06d2e4-c080-11e7-8e5b-145d8236ad82.png)

This might have some relation to issue #163 (redux-persist being way too aggressive), maybe due to that I see packages in the UI but not in the tests? Is this expected:
```
❱❱❱ curl http://localhost:4000/api/v0/modules/list
{"modules":[],"offset":0,"limit":20,"total":0}
```
I'm not sure if `/modules` also covers packages, but there is no `/packages/` like path, and core/constants.js does not have something package related either. So I suppose my api container is somehow broken and does not actually contain the right metadata.db?

**Comment by martinpitt** [comment]
That was indeed the case. Apparently my "api" container from a previous local dockerized test run wasn't defined properly and didn't bind-mount the correct metadata.db. When I re-run it with

    sudo docker run --name api --rm -p 4000:4000 -v bdcs-recipes-volume:/bdcs-recipes -v `pwd`:/mddb --security-opt label=disable welder/bdcs-api-rs:latest

then the test actually succeeds, and curl shows me lots of data on /api/v0/modules/list too.
